version: '3'

# certbot container automated test compose file.

services:
  pebble:
    image: letsencrypt/pebble:latest
    command: pebble -config /test/config/pebble-config.json -dnsserver 10.30.50.3:8053
    ports:
      - 14000:14000  # HTTPS ACME API
      - 15000:15000  # HTTPS Management API
    networks:
      acmenet:
        ipv4_address: 10.30.50.2
  challtestsrv:
    image: letsencrypt/pebble-challtestsrv:latest
    command: pebble-challtestsrv -defaultIPv6 "" -defaultIPv4 10.30.50.3
    ports:
      - 8055:8055  # HTTP Management API
    networks:
      acmenet:
        ipv4_address: 10.30.50.3
  sut:
    image: lochnerr/certbot:latest
    command: /usr/local/bin/certbot-test
    restart: "no"
    hostname: sut.example.com
    networks:
      acmenet:
        ipv4_address: 10.30.50.4
    depends_on:
      - pebble
      - challtestsrv

networks:
  acmenet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.30.50.0/24

